name: CI-Pipeline

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:

  codeql-python:
    name: CodeQL Python Scan
    runs-on: ubuntu-24.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  docker-build:
    name: Docker Build & Scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: local/test:latest

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: local/test:latest
          format: table
          exit-code: 0

  dependency-check:
    name: OWASP Dependency Check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: OWASP Scan
        uses: dependency-check/Dependency-Check_Action@v3.0.3
        with:
          project: "TENET"
          path: "."

  secret-scan:
    name: GitGuardian Secret Scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GitGuardian Scan
        uses: GitGuardian/ggshield-action@v1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GGSHIELD_API_KEY: ${{ secrets.GG_API_KEY }}
